// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtyXjPEZaP9RmhDjGody-h8hQbihILIhQ',
    appId: '1:827979449878:android:4843b84447ea6e65219737',
    messagingSenderId: '827979449878',
    projectId: 'agriguard-ca00b',
    databaseURL: 'https://agriguard-ca00b-default-rtdb.firebaseio.com',
    storageBucket: 'agriguard-ca00b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLNtdRXAobUDqmxM9iZMwcv9Ik0a5A_q4',
    appId: '1:827979449878:ios:f4b7a8a55932575e219737',
    messagingSenderId: '827979449878',
    projectId: 'agriguard-ca00b',
    databaseURL: 'https://agriguard-ca00b-default-rtdb.firebaseio.com',
    storageBucket: 'agriguard-ca00b.firebasestorage.app',
    iosClientId: '827979449878-udlv9h5p727jfaq762qsa9jsrhlkj5ka.apps.googleusercontent.com',
    iosBundleId: 'com.agriguard.agriguardProject',
  );
}
